### ISSUE TITLE
Add support for text selection

### ISSUE THREAD

**Issue by herronelou** [TerryGeng/termqt#13]
The Terminal widget currently lacks a key feature, which is the ability to select text using the mouse for copying.

**Comment by TerryGeng** [comment]
Yes, I agree. Clipboard-related features are on the to-do list. I just need to find some time to implement it.

I'm a full-time Ph.D. student and have a lot of time commitment to my experiment. To be honest, I'm quite surprised (and happy) to see some things I scrambled during a weekend a few years ago can gain such attention from the community.

Currently, all I can do is to spend part of my weekend working on it. I would definitely like to see more developers jumping in as contributors and taking some duties off my shoulder :). However, before that happens, please expect some delay.

**Comment by herronelou** [comment]
That's alright, this is the case for a lot of open source software out there.
I'm also willing to take a look at implementing myself, though in my case it's my job taking most of my time, and also trying to fit in extra during the weekend.

**Comment by TerryGeng** [comment]
Implemented by #19.
