### ISSUE TITLE
an issue with clear buffer

### ISSUE THREAD

**Issue by mohammadkarami2023** [TerryGeng/termqt#26]
I have used termqt in a tab inside a qdialog. whenever i reopen the dialog i use terminal.clear_buffer() to clear the screen but after some tries i get the following errors:
Traceback (most recent call last):

  File ~/.local/lib/python3.8/site-packages/termqt/terminal_widget.py:658 in resize
    self.resize(self.size().width(), self.size().height())

  File ~/.local/lib/python3.8/site-packages/termqt/terminal_widget.py:451 in resize
    self._save_cursor_state_stop_blinking()

  File ~/.local/lib/python3.8/site-packages/termqt/terminal_widget.py:527 in _save_cursor_state_stop_blinking
    self._switch_cursor_blink(CursorState.ON, False)

  File ~/.local/lib/python3.8/site-packages/termqt/terminal_widget.py:522 in _switch_cursor_blink
    self._paint_cursor()

  File ~/.local/lib/python3.8/site-packages/termqt/terminal_widget.py:416 in _paint_cursor
    c = self._buffer[ind_y][chr_x]

IndexError: deque index out of range

QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setPen: Painter not active
QPainter::setFont: Painter not active

**Comment by TerryGeng** [comment]
This is a good catch. `paint_cursor` doesn't check if the cursor is in the valid buffer region. I posted a quick fix #27. Would you please confirm it solves this bug?

On the other hand, I would suggest you reset the cursor position to (0, 0) after clearing the buffer to avoid the cursor position surprising you.

**Comment by mohammadkarami2023** [comment]
thanks, clear buffer now works. another issue happens when the initial command fails. i get the following:
Traceback (most recent call last):

  File ~/.local/lib/python3.8/site-packages/termqt/terminal_widget.py:545 in _stdout
    need_draw = self._stdout_string(string)

  File ~/.local/lib/python3.8/site-packages/termqt/terminal_buffer.py:1378 in _stdout_string
    self.write_at_cursor(tst_buf)

  File ~/.local/lib/python3.8/site-packages/termqt/terminal_buffer.py:1051 in write_at_cursor
    self.write(text, pos=None, set_cursor=True, reset_offset=False)

  File ~/.local/lib/python3.8/site-packages/termqt/terminal_buffer.py:1027 in write
    buf[pos_y][pos_x] = t

IndexError: list assignment index out of range

**Comment by mohammadkarami2023** [comment]
I also modified the last lines of start.py to test the functionality of clear_buffer. no exceptions happens but in the terminal the current dir is shown twice.
`terminal_io.stdout_callback = terminal.stdout
    terminal.stdin_callback = terminal_io.write
    terminal.resize_callback = terminal_io.resize
    terminal_io.spawn()
    terminal.clear_buffer()
    terminal_io.terminate()
    terminal_io.spawn()
    terminal.set_cursor_position(0, 0)
    terminal.clear_buffer()
    terminal.set_cursor_position(0, 0)

    sys.exit(app.exec())`

Terminal looks like

mohammad@mypc:~/Downloads/termqt-240fda2253750944cc922b329ce2d72318de1b78$mohammad@mypc:~/Downloads/termqt-240fda2253750944cc922b329ce2d72318de1b78$

**Comment by TerryGeng** [comment]
Great to know!

Thanks again!

**Comment by TerryGeng** [comment]
Regarding the new issue of lines being displayed twice, I would think it is an issue with the shell itself (since the shell doesn't know the buffer is cleared). I may look into it a bit more today.

**Comment by mohammadkarami2023** [comment]
oh i realized that there is no problem with command top but the font is black similar to the background.
also is there anyway to change the background of the widget?

**Comment by TerryGeng** [comment]
Why the foreground color is black in your case? I believe the default color is white. Can you investigate this?

**Comment by mohammadkarami2023** [comment]
my foreground is white. when i execute top command in the bash, the summary of my resources are shown as white,  but the processes have black font color

**Comment by mohammadkarami2023** [comment]
it seems that the lines that get updated have black foreground color. in my case even the upper lines after a while become black as shown in the following pictures
![test](https://github.com/TerryGeng/termqt/assets/144117627/4e3347e3-26bf-476c-916e-3e76345ade43)
![test1](https://github.com/TerryGeng/termqt/assets/144117627/fde97df7-bd32-45bf-a076-34222ef131d6)

**Comment by TerryGeng** [comment]
I see. The issue is caused by some broken support for some escape sequences. I have pushed a new commit to #27. Would you have a look?

**Comment by mohammadkarami2023** [comment]
Thank you, the problem has resolved. Before, this commit even editing the command just entered could cause changing foreground color. There is another issue. Editing the line just entered has another issue. inserting a character beore space works like pressing "insert" key of the keyboard. For example enter "Hello World", place the cursor before the space, enter a character, place left arrow and again press a key. in normal mode inserting a char does not replace the character the cursor is on. but doing so, the mode suddenly changes
