### ISSUE TITLE
Editing command

### ISSUE THREAD

**Issue by mohammadkarami2023** [TerryGeng/termqt#28]
Editing the line just entered has issue. inserting a character before "space" works like pressing "insert" key of the keyboard. For example enter "Hello World", place the cursor before the space, enter a character, press left arrow and again press a key. in normal mode inserting a char does not replace the character the cursor is on. but doing so, the mode suddenly changes

**Comment by TerryGeng** [comment]
This bug has been reproduced and is caused by missing the implementation of `ESC [ <N> @` sequence ([Insert Blanks](https://terminalguide.namepad.de/seq/csi_x40_at/)). Will fix this week.

**Comment by mohammadkarami2023** [comment]
Thanks

**Comment by TerryGeng** [comment]
Sorry for the long delay. I'm caught up in my other responsibilities.

Would you have a look at the new PR #29?

**Comment by mohammadkarami2023** [comment]
thanks. seems working
